import { FormEvent, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Brand } from '../components/Brand'
import { acceptAgreement, getSharedAgreement, requestChanges, signAgreement } from '../lib/agreements'
import { supabase } from '../lib/supabase'

type SharedDeal=Record<string,string|number|boolean|null>
const money=(minor:number)=>new Intl.NumberFormat('en-MY',{style:'currency',currency:'MYR'}).format(minor/100)
export function RecipientDealPage(){
 const {token=''}=useParams();const [email,setEmail]=useState(()=>sessionStorage.getItem(`okdeal-email-${token}`)||'');const [deal,setDeal]=useState<SharedDeal|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [action,setAction]=useState<'changes'|'accept'|'sign'|null>(null);const [message,setMessage]=useState('');const [name,setName]=useState('');const [verified,setVerified]=useState(false)
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setVerified(data.user?.email?.toLowerCase()===email.toLowerCase()))},[email])
 async function review(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await getSharedAgreement(token,email);if(!result)setError('Those details do not match the intended recipient.');else{setDeal(result as SharedDeal);sessionStorage.setItem(`okdeal-email-${token}`,email)}}catch{setError('We could not open this OKDeal. Check the link and try again.')}finally{setBusy(false)}}
 async function verify(){setBusy(true);setError('');try{const {data}=await supabase.auth.getUser();if(data.user&&data.user.email?.toLowerCase()!==email.toLowerCase())await supabase.auth.signOut();const {error:e}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href,shouldCreateUser:true}});if(e)throw e;setError('Verification email sent. Open its link, then return here to continue.')}catch(e){setError(e instanceof Error?e.message:'Could not send verification email.')}finally{setBusy(false)}}
 async function perform(){if(!verified)return verify();setBusy(true);setError('');try{if(action==='changes'){await requestChanges(token,message);setDeal({...deal!,status:'changes_requested'})}if(action==='accept'){await acceptAgreement(token);setDeal({...deal!,status:'awaiting_signatures',accepted_version:deal!.version_number})}if(action==='sign'){await signAgreement(String(deal!.id),token,'recipient',name);setDeal(await getSharedAgreement(token,email) as SharedDeal)}setAction(null)}catch(e){setError(e instanceof Error?e.message:'Could not complete this action.')}finally{setBusy(false)}}
 if(!deal)return <div className="create-page"><header className="create-header"><Brand/><Link to="/">About OKDeal</Link></header><main className="auth-shell"><section className="auth-card"><p className="eyebrow">PRIVATE AGREEMENT LINK</p><h1>Is this OKDeal for you?</h1><p>Enter the email address the creator used. This confirms the agreement is addressed to you; it does not prove legal identity.</p>{error&&<div className="draft-notice" role="alert">{error}</div>}<form onSubmit={review}><label>Recipient email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="button" disabled={busy}>{busy?'Checking…':'Confirm and review'}</button></form></section></main></div>
 const status=String(deal.status);const signed=Boolean(deal.recipient_signed)
 return <div className="preview-page"><header className="create-header"><Brand/><span className="save-state">{String(deal.okdeal_id)} · Version {String(deal.version_number)}</span></header><main className="recipient-main">{error&&<div className="draft-notice" role="status">{error}</div>}<article className="agreement-preview printable"><div className="preview-top"><span>OKDeal · {status.replaceAll('_',' ')}</span><span>{String(deal.okdeal_id)}</span></div><div className="agreement-heading"><p className="eyebrow">WORK / SERVICE AGREEMENT</p><h2>{String(deal.title)}</h2><p>Review this exact version carefully before responding.</p></div><section className="preview-section"><h3>Intended recipient</h3><strong>{String(deal.intended_recipient_name)}</strong></section><section className="preview-section"><h3>Work</h3><p className="agreement-text">{String(deal.description)}</p></section><section className="preview-section"><h3>Terms</h3><dl className="terms-grid"><div><dt>Amount</dt><dd>{money(Number(deal.amount_minor))}</dd></div><div><dt>Dates</dt><dd>{String(deal.start_date)} – {String(deal.completion_date)}</dd></div><div><dt>Payment terms</dt><dd>{String(deal.payment_terms)}</dd></div>{deal.additional_terms&&<div><dt>Additional terms</dt><dd>{String(deal.additional_terms)}</dd></div>}</dl></section><div className="preview-stamp">{status==='completed'?'COMPLETED · LOCKED RECORD':'VERSIONED RECORD · NOT LOCKED'}</div></article>
 {status==='awaiting_review'&&<div className="recipient-actions"><button className="button button-secondary" onClick={()=>setAction('changes')}>Request changes</button><button className="button" onClick={()=>setAction('accept')}>Accept & agree</button></div>}{status==='changes_requested'&&<div className="coming-next"><strong>Changes requested.</strong><p>The creator can now propose a new version. This version remains in history.</p></div>}{status==='awaiting_signatures'&&!signed&&<div className="recipient-actions"><button className="button" onClick={()=>setAction('sign')}>Sign Version {String(deal.version_number)}</button></div>}{signed&&status!=='completed'&&<div className="coming-next"><strong>You signed this version.</strong><p>The agreement will lock after the creator also signs.</p></div>}{status==='completed'&&<button className="button pdf-button" onClick={()=>window.print()}>Save completed record as PDF</button>}
 {action&&<div className="action-card"><h2>{action==='changes'?'Request changes':action==='accept'?'Accept this version':'Sign this version'}</h2>{!verified&&<p>We will email a secure verification link to <strong>{email}</strong>. This verifies mailbox control, not legal identity.</p>}{action==='changes'&&<label>What should change?<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={3000}/></label>}{action==='sign'&&<><label>Your full name<input value={name} onChange={e=>setName(e.target.value)} maxLength={150}/></label><p>By signing, you confirm you reviewed Version {String(deal.version_number)} and intend to sign it electronically.</p></>}<div className="recipient-actions"><button className="text-button" onClick={()=>setAction(null)}>Cancel</button><button className="button" disabled={busy||(action==='changes'&&!message.trim())||(action==='sign'&&name.trim().length<2)} onClick={perform}>{busy?'Please wait…':verified?'Confirm action':'Verify email'}</button></div></div>}
 </main></div>
}
